version: "3.3"

services:
  postgres:
    image: postgres:12.13-alpine
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: default
      POSTGRES_PASSWORD: password
    networks:
      - local_network

  nginx:
    image: nginx:1.24.0-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local_network
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - .:/app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: default
      DB_USER: default
      DB_PASS: password
    networks:
      - local_network
    depends_on:
      - postgres

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    command: python client/send_request.py
    volumes:
      - .:/app
    networks:
      - local_network
    depends_on:
      - server

  pgadmin:
    image: dpage/pgadmin4:6.18
    ports:
      - "5051:80"
    volumes:
      - ./.pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=default@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - local_network
    depends_on:
      - postgres

networks:
  local_network:
    driver: bridge
